version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_ENVIRONMENT}
    tty: true
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/opt/app/api
      - files-uploaded:/opt/app/files-uploaded
      - database-backup:/opt/app/database-backup
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3010:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - internal

  adminer:
    image: adminer:4.8.1-standalone
    container_name: tripgo-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8005:8080"
    networks:
      - internal

  db:
    image: postgres:16
    container_name: tripgo-db
    restart: on-failure
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - tripgo-db:/var/lib/postgresql/data"
    networks:
      - internal

networks:
  internal:
    driver: bridge
volumes:
  tripgo-db:
    driver: local
  files-uploaded:
    driver: local
  database-backup:
    driver: local
