# map "$http_origin" $cors {
#       default '';
#       "~^https?:\/\/(localhost|www\.yourdomain\.com|www\.yourotherdomain\.com)" "$http_origin";
#       #"~^http?:\/\/\w+(:[0-9]*)?(\.\w+)?$" "$http_origin";
#       #"~^http?://195.35.20.241?$" "$http_origin";
# }

server {
   listen 8000 default_server;
   listen [::]:8000 default_server ipv6only=on;

   keepalive_timeout 30;
   client_max_body_size 100M;
   large_client_header_buffers 4 16k;

   location / {
#       proxy_hide_header 'Access-Control-Allow-Origin';
#       proxy_hide_header 'Access-Control-Allow-Credentials';
#       proxy_hide_header 'Access-Control-Allow-Methods';
#       proxy_hide_header 'Access-Control-Allow-Headers';
#
#        # Attach CORS headers only if it's a valid origin ($cors should not be empty)
#                    if ($cors != "") {
#                            add_header 'Access-Control-Allow-Origin' "$cors" always; # <-- Variable $cors
#                            add_header 'Access-Control-Allow-Credentials' 'true' always;
#                            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
#                            add_header 'Access-Control-Allow-Headers' 'Accept, Authorization, Cache-Control, Content-Type, DNT, If-Modified-Since, Keep-Alive, Origin, User-Agent, X-Requested-With' always;
#                    }
#
#        # Check if it's a preflight request and "cache" it for 20 days
#                    if ($request_method = 'OPTIONS') {
#                            add_header 'Access-Control-Allow-Origin' "$cors" always;
#                            add_header 'Access-Control-Max-Age' 1728000;
#                            add_header 'Access-Control-Allow-Credentials' 'true' always;
#                            add_header 'Access-Control-Allow-Headers' "Content-Type, Accept, Cache-Control, Authorization, Keep-Alive, Origin, User-Agent, X-Requested-With" always;
#                            add_header 'Content-Type' 'text/plain charset=UTF-8';
#                            add_header 'Content-Length' 0;
#                            return 204;
#                    }

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://app:3010;
    }

    location = /favicon.ico {
      return 204;
      access_log     off;
      log_not_found  off;
    }
}
