definitions:
  dto.CustomerSignup:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - email
    - name
    - password
    type: object
  dto.DriverSignup:
    properties:
      driverType:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - email
    - name
    - password
    type: object
  dto.InsertBookingTransfer:
    properties:
      adultSeater:
        type: integer
      carModelId:
        type: string
      childSeater:
        type: integer
      fromLatCoordinate:
        type: number
      fromLngCoordinate:
        type: number
      fromLocation:
        type: string
      id:
        type: string
      passengerNotes:
        type: string
      pickUpDate:
        type: string
      price:
        type: number
      toLatCoordinate:
        type: number
      toLngCoordinate:
        type: number
      toLocation:
        type: string
      totalDistance:
        type: number
    type: object
  dto.Response:
    properties:
      code:
        type: integer
      data: {}
      error: {}
      kind:
        type: string
      message:
        type: string
    type: object
  dto.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.UserSignup:
    properties:
      address:
        type: string
      createdBy:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /auth/c/signin:
    post:
      consumes:
      - application/json
      description: A Customer authentication sign-in method
      parameters:
      - description: customer login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Customer Sign-In
      tags:
      - Authentication - Customer
  /auth/c/signup:
    post:
      consumes:
      - application/json
      description: Customer Sign-Up
      parameters:
      - description: customer registration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.CustomerSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Customer Sign-Up
      tags:
      - Authentication - Customer
  /auth/d/signin:
    post:
      consumes:
      - application/json
      description: A Driver authentication sign-in method for mobile apps
      parameters:
      - description: driver login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Driver Sign-In
      tags:
      - Authentication - Driver
  /auth/d/signup:
    post:
      consumes:
      - application/json
      description: Driver Sign-Up
      parameters:
      - description: driver registration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.DriverSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Driver Sign-Up
      tags:
      - Authentication - Driver
  /auth/i/signup:
    post:
      consumes:
      - application/json
      description: Internal Sign-Up
      parameters:
      - description: internal registration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Internal Sign-Up
      tags:
      - Authentication - Internal
  /booking-assigned/transfer:
    get:
      consumes:
      - application/json
      description: A GET Request to fetch a all records for driver to view booking
        transfer that assigned and whose are not accepted by the driver
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: List Booking Transfer Assigned
      tags:
      - Booking Assgined - Transfer
  /booking-assigned/transfer/accept:
    get:
      consumes:
      - application/json
      description: A GET Request to fetch a all records for driver to view booking
        transfer that assigned and whose are not accepted by the driver
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Method to accept booking transfer request
      tags:
      - Booking Assgined - Transfer
  /booking-assigned/transfer/cancel:
    get:
      consumes:
      - application/json
      description: A GET Request to fetch a all records for driver to view booking
        transfer that assigned and whose are not accepted by the driver
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Method to cancel booking transfer request
      tags:
      - Booking Assgined - Transfer
  /booking/transfer:
    post:
      consumes:
      - application/json
      description: A POST Request to create a new record for costumer to make a new
        Transfer booking to the driver
      parameters:
      - description: insert booking transfer
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.InsertBookingTransfer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Method to create booking transfer request by customer
      tags:
      - Booking - Transfer
  /booking/transfer/all:
    get:
      consumes:
      - application/json
      description: A GET Request to fetch a all records for customer to view booking
        transfer that already created
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Method to get all booking transfer made by customer
      tags:
      - Booking - Transfer
  /car-management/create:
    post:
      consumes:
      - application/json
      description: A POST Request to create a car and assigned to the driver whose
        creating it
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - in: formData
        name: carManagementType
        required: true
        type: string
      - in: formData
        name: carModelId
        required: true
        type: string
      - in: formData
        name: driverID
        type: string
      - in: formData
        name: licensePhoto
        type: string
      - in: formData
        name: name
        required: true
        type: string
      - in: formData
        name: plateNumber
        required: true
        type: string
      - description: front car photo upload
        in: formData
        name: frontCarPhoto
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Method to create or assign a car to the driver
      tags:
      - Car Management
  /web/statistic/customer:
    get:
      consumes:
      - application/json
      description: A GET Request to fetch count how many bookings are made by customer
        either transfer, tour or delivery
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Method to count booking transfer by customer
      tags:
      - Booking - Transfer
swagger: "2.0"
