definitions:
  dto.CustomerSignup:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - email
    - name
    - password
    - phone
    type: object
  dto.DriverSignup:
    properties:
      driverType:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - driverType
    - email
    - name
    - password
    - phone
    type: object
  dto.Response:
    properties:
      code:
        type: integer
      data: {}
      error: {}
      kind:
        type: string
      message:
        type: string
    type: object
  dto.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.UserSignup:
    properties:
      address:
        type: string
      createdBy:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /auth/c/signup:
    post:
      consumes:
      - application/json
      description: Customer Sign-Up
      parameters:
      - description: customer registration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.CustomerSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Customer Sign-Up
      tags:
      - Authentication - Customer
  /auth/d/signup:
    post:
      consumes:
      - application/json
      description: Driver Sign-Up
      parameters:
      - description: driver registration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.DriverSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Driver Sign-Up
      tags:
      - Authentication - Driver
  /auth/i/signup:
    post:
      consumes:
      - application/json
      description: Internal Sign-Up
      parameters:
      - description: internal registration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Internal Sign-Up
      tags:
      - Authentication - Internal
  /auth/signin:
    post:
      consumes:
      - application/json
      description: A Global authentication sign-in method for all microservices
      parameters:
      - description: global login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Global Sign-In
      tags:
      - Authentication - Global
swagger: "2.0"
